# Generated by Django 4.2.23 on 2025-09-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_product_picture_product_specific"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="specific",
        ),
        migrations.AddField(
            model_name="product",
            name="specfile",
            field=models.FileField(blank=True, null=True, upload_to="specfile"),
        ),
    ]
