# Generated by Django 4.2.3 on 2025-10-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_prompt_testcase_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='prompt_attachments'),
        ),
    ]
